Linked in bug fix
 Error: You must specify a valid JavaScript API Domain as part of this key's configuration.

I had to make this change in order to fix the above error and everything works fine now.